name: audio_client
description: Audio streaming Flutter application
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # =========================
  # State Management
  # =========================
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  # =========================
  # Routing
  # =========================
  go_router: ^16.0.0

  # =========================
  # Networking
  # =========================
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0

  # =========================
  # Audio
  # =========================
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  just_audio: ^0.10.5

  # =========================
  # Models
  # =========================
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # =========================
  # Firebase
  # =========================
  firebase_analytics: ^12.0.0
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  firebase_remote_config: ^6.0.0

  # =========================
  # Storage
  # =========================
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # =========================
  # Utils
  # =========================
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.1.0
  intl: ^0.20.2
  logger: ^2.6.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.5
  uuid: ^4.5.1

  # =========================
  # UI
  # =========================
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  shimmer: ^3.0.0

  # =========================
  # Environment
  # =========================
  flutter_dotenv: ^5.2.1

  # =========================
  # Download / Permissions
  # =========================
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.1

  # =========================
  # Deep Link
  # =========================
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^9.0.0

  # =========================
  # Code Generation
  # =========================
  build_runner: ^2.7.0
  custom_lint: ^0.8.0

  # Freezed / JSON
  freezed: ^3.1.0
  json_serializable: ^6.11.1

  # Riverpod
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod